### ISSUE TITLE
Marking build as UNSTABLE in case of some Mabl journey tests fail

### ISSUE THREAD

**Issue by davesade** [jenkinsci/mabl-integration-plugin#21]
Hello!
Some of our Jenkins pipelines do fail during Mabl journey testing.
I'm aware of `continueOnPlanFailure`, which does the job - but then whole pipeline is marked as SUCCESS.
My intention is to set build result as UNSTABLE in case Mabl fails during testing - it should not stop the pipeline. At the same time, with UNSTABLE result we will be notified something needs our attention.

**Comment by twistedpair** [comment]
Thanks for the feedback, @davesade . That's a great suggestion to provide better clarity into what happened during test execution.

We track mabl feedback through our [feedback portal](https://feedback.mabl.com). Please add this request there and you'll be able to vote on it and track it's progress. :+1:
